export interface CatalogItem {
  name: string
  category: string
  price: string
  nighttimeAvailable: string
  restrictedFlag: string
  imageUrl?: string
}

export const PRESET_CATALOG: CatalogItem[] = [
  // Energy & Drinks
  { name: 'Red Bull 8.4oz', category: 'Energy Drinks', price: '4.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Red Bull Sugar Free 8.4oz', category: 'Energy Drinks', price: '4.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Monster Energy Original 16oz', category: 'Energy Drinks', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Monster Zero Ultra 16oz', category: 'Energy Drinks', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Celsius Sparkling Orange 12oz', category: 'Energy Drinks', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: '5-hour ENERGY Extra Strength', category: 'Energy Drinks', price: '4.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Gatorade Fruit Punch 32oz', category: 'Sports Drinks', price: '3.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Gatorade Lemon-Lime 32oz', category: 'Sports Drinks', price: '3.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Powerade Mountain Berry Blast 32oz', category: 'Sports Drinks', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Liquid IV Hydration Multiplier', category: 'Sports Drinks', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Smartwater 1L', category: 'Water', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'FIJI Water 1L', category: 'Water', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Evian Natural Spring Water 1L', category: 'Water', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Essentia 9.5 pH Water 1L', category: 'Water', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Coca-Cola 20oz', category: 'Soft Drinks', price: '2.79', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Diet Coke 20oz', category: 'Soft Drinks', price: '2.79', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Sprite 20oz', category: 'Soft Drinks', price: '2.79', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Dr Pepper 20oz', category: 'Soft Drinks', price: '2.79', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Mountain Dew 20oz', category: 'Soft Drinks', price: '2.79', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Arizona Green Tea 23oz', category: 'Soft Drinks', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Lipton Brisk Iced Tea 20oz', category: 'Soft Drinks', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Tropicana Orange Juice 10oz', category: 'Juice', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Minute Maid Lemonade 20oz', category: 'Juice', price: '2.79', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Starbucks Frappuccino Mocha 13.7oz', category: 'Coffee', price: '4.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Starbucks Double Shot Espresso 6.5oz', category: 'Coffee', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Monster Java Mean Bean 15oz', category: 'Coffee', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  // Snacks
  { name: 'Doritos Nacho Cheese 2.75oz', category: 'Chips', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Doritos Cool Ranch 2.75oz', category: 'Chips', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: "Lay's Classic 2.625oz", category: 'Chips', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: "Lay's Sour Cream & Onion 2.625oz", category: 'Chips', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Cheetos Crunchy 2.375oz', category: 'Chips', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Fritos Original 2oz', category: 'Chips', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Pringles Original 2.5oz', category: 'Chips', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Takis Fuego 3.2oz', category: 'Chips', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Kettle Brand Sea Salt 2oz', category: 'Chips', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Snickers 1.86oz', category: 'Candy', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Snickers King Size 3.29oz', category: 'Candy', price: '3.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: "Reese's Peanut Butter Cups 1.5oz", category: 'Candy', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: "Reese's King Size 2.8oz", category: 'Candy', price: '3.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Kit Kat 1.5oz', category: 'Candy', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Twix 1.79oz', category: 'Candy', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'M&Ms Peanut 1.74oz', category: 'Candy', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Skittles Original 2.17oz', category: 'Candy', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Starburst Original 2.07oz', category: 'Candy', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Haribo Gold-Bears 4oz', category: 'Candy', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Airheads Variety 3.3oz', category: 'Candy', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Nature Valley Oats & Honey Bar', category: 'Bars', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Clif Bar Chocolate Chip', category: 'Bars', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Kind Dark Chocolate Nuts & Sea Salt', category: 'Bars', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'RXBar Chocolate Sea Salt', category: 'Bars', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Planters Dry Roasted Peanuts 1.75oz', category: 'Nuts', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Planters Mixed Nuts 1.75oz', category: 'Nuts', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Sunflower Seeds David Original 1.75oz', category: 'Nuts', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  // Food
  { name: 'Slim Jim Original 0.97oz', category: 'Meat Snacks', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Slim Jim Giant 1.94oz', category: 'Meat Snacks', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Jack Links Beef Jerky 1.25oz', category: 'Meat Snacks', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Old Wisconsin Turkey Stick', category: 'Meat Snacks', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Hot Dog – Roller Grill', category: 'Hot Food', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Cheeseburger – Heated', category: 'Hot Food', price: '4.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Taquito – Chicken', category: 'Hot Food', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Taquito – Beef', category: 'Hot Food', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: "Chester's Fries 1.75oz", category: 'Hot Food', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Pop-Tarts Frosted Strawberry 2pk', category: 'Pastry', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Honey Bun', category: 'Pastry', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Donettes Powdered Mini Donuts 3oz', category: 'Pastry', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  // Health & Personal Care
  { name: 'Advil Ibuprofen 200mg 10ct', category: 'Pain Relief', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Tylenol Extra Strength 10ct', category: 'Pain Relief', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Aleve 220mg 8ct', category: 'Pain Relief', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Pepto-Bismol Chewable 4ct', category: 'Stomach', price: '5.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Tums Ultra Strength 12ct', category: 'Stomach', price: '4.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Tylenol PM 10ct', category: 'Sleep', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'ZzzQuil Nighttime Sleep Aid 12ct', category: 'Sleep', price: '9.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Unisom SleepTabs 8ct', category: 'Sleep', price: '8.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Trojan ENZ Condoms 3pk', category: 'Personal Care', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Trojan Ultra Thin 3pk', category: 'Personal Care', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Durex Extra Sensitive 3pk', category: 'Personal Care', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Chapstick Original', category: 'Personal Care', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: "Burt's Bees Lip Balm", category: 'Personal Care', price: '4.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Visine Original Eye Drops 0.5oz', category: 'Personal Care', price: '7.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Listerine PocketPaks Strips 24ct', category: 'Personal Care', price: '4.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Colgate Wisp Disposable Toothbrush', category: 'Personal Care', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  // === Cigarettes (Restricted) ===
  // Marlboro
  { name: 'Marlboro Red (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro Red 100s (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro Gold (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro Gold 100s (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro Silver (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro Menthol (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro Menthol 100s (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro Menthol Gold (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro Black (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro Black Menthol (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro Southern Cut (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro Bold Ice Menthol (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro Skyline Menthol (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro Midnight Menthol (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro Smooth Menthol (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro 72s Red (pack)', category: 'Cigarettes', price: '12.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro 72s Gold (pack)', category: 'Cigarettes', price: '12.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Newport
  { name: 'Newport Menthol Kings (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Newport Menthol 100s (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Newport Menthol Gold Kings (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Newport Menthol Gold 100s (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Newport Platinum Menthol 100s (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Newport Red Kings (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Newport Red 100s (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Camel
  { name: 'Camel Filters Kings (pack)', category: 'Cigarettes', price: '11.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Camel Filters 99s (pack)', category: 'Cigarettes', price: '11.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Camel Blue Kings (pack)', category: 'Cigarettes', price: '11.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Camel Blue 99s (pack)', category: 'Cigarettes', price: '11.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Camel Crush Rich Menthol (pack)', category: 'Cigarettes', price: '12.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Camel Crush Bold Menthol (pack)', category: 'Cigarettes', price: '12.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Camel Crush Fresh (pack)', category: 'Cigarettes', price: '12.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Camel Menthol Silver (pack)', category: 'Cigarettes', price: '11.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Camel Turkish Gold (pack)', category: 'Cigarettes', price: '11.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Camel Turkish Royal (pack)', category: 'Cigarettes', price: '11.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Camel Turkish Silver (pack)', category: 'Cigarettes', price: '11.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Natural American Spirit
  { name: 'American Spirit Yellow (pack)', category: 'Cigarettes', price: '14.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'American Spirit Blue (pack)', category: 'Cigarettes', price: '14.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'American Spirit Orange (pack)', category: 'Cigarettes', price: '14.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'American Spirit Green Menthol (pack)', category: 'Cigarettes', price: '14.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'American Spirit Dark Blue (pack)', category: 'Cigarettes', price: '14.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'American Spirit Celadon Menthol (pack)', category: 'Cigarettes', price: '14.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'American Spirit Black (pack)', category: 'Cigarettes', price: '14.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'American Spirit Turquoise Menthol (pack)', category: 'Cigarettes', price: '14.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Pall Mall
  { name: 'Pall Mall Red Kings (pack)', category: 'Cigarettes', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Pall Mall Red 100s (pack)', category: 'Cigarettes', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Pall Mall Blue Kings (pack)', category: 'Cigarettes', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Pall Mall Blue 100s (pack)', category: 'Cigarettes', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Pall Mall Orange 100s (pack)', category: 'Cigarettes', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Pall Mall Menthol Kings (pack)', category: 'Cigarettes', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Pall Mall Menthol 100s (pack)', category: 'Cigarettes', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Pall Mall Black 100s (pack)', category: 'Cigarettes', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Winston
  { name: 'Winston Red Kings (pack)', category: 'Cigarettes', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Winston Red 100s (pack)', category: 'Cigarettes', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Winston White Kings (pack)', category: 'Cigarettes', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Winston Gold 100s (pack)', category: 'Cigarettes', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Winston Menthol Kings (pack)', category: 'Cigarettes', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Parliament
  { name: 'Parliament White Kings (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Parliament Silver 100s (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Parliament Light 100s (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Parliament Menthol Silver 100s (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Parliament Full Flavor 100s (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Lucky Strike
  { name: 'Lucky Strike Original Red (pack)', category: 'Cigarettes', price: '11.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Lucky Strike Filters (pack)', category: 'Cigarettes', price: '11.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // L&M
  { name: 'L&M Red Kings (pack)', category: 'Cigarettes', price: '9.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'L&M Red 100s (pack)', category: 'Cigarettes', price: '9.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'L&M Blue 100s (pack)', category: 'Cigarettes', price: '9.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'L&M Menthol 100s (pack)', category: 'Cigarettes', price: '9.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Kool
  { name: 'Kool Filter Kings Menthol (pack)', category: 'Cigarettes', price: '11.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Kool Menthol 100s (pack)', category: 'Cigarettes', price: '11.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Kool Blue Menthol 100s (pack)', category: 'Cigarettes', price: '11.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Kool Green Menthol 100s (pack)', category: 'Cigarettes', price: '11.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Virginia Slims
  { name: 'Virginia Slims Menthol Silver 100s (pack)', category: 'Cigarettes', price: '12.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Virginia Slims Ultra Lights 100s (pack)', category: 'Cigarettes', price: '12.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Benson & Hedges
  { name: 'Benson & Hedges Deluxe Ultra 100s (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Benson & Hedges Menthol Gold 100s (pack)', category: 'Cigarettes', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Capri
  { name: 'Capri Menthol Magenta 120s (pack)', category: 'Cigarettes', price: '12.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Capri Menthol Sea Green 120s (pack)', category: 'Cigarettes', price: '12.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Misty / Salem
  { name: 'Misty Gold 100s (pack)', category: 'Cigarettes', price: '9.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Salem Black Label (pack)', category: 'Cigarettes', price: '11.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Salem Gold 100s (pack)', category: 'Cigarettes', price: '11.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Maverick / Eagle 20 / Doral / Basic / USA Gold (economy)
  { name: 'Maverick Red 100s (pack)', category: 'Cigarettes', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Maverick Menthol 100s (pack)', category: 'Cigarettes', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Eagle 20 Red 100s (pack)', category: 'Cigarettes', price: '8.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Eagle 20 Menthol 100s (pack)', category: 'Cigarettes', price: '8.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Doral Red 100s (pack)', category: 'Cigarettes', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Doral Menthol 100s (pack)', category: 'Cigarettes', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Basic Red 100s (pack)', category: 'Cigarettes', price: '9.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Basic Menthol 100s (pack)', category: 'Cigarettes', price: '9.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'USA Gold Red 100s (pack)', category: 'Cigarettes', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'USA Gold Menthol 100s (pack)', category: 'Cigarettes', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Montego Red 100s (pack)', category: 'Cigarettes', price: '7.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Montego Menthol 100s (pack)', category: 'Cigarettes', price: '7.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Pyramid Red 100s (pack)', category: 'Cigarettes', price: '7.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Pyramid Menthol 100s (pack)', category: 'Cigarettes', price: '7.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Sonoma Red 100s (pack)', category: 'Cigarettes', price: '8.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Sonoma Menthol 100s (pack)', category: 'Cigarettes', price: '8.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Imports / specialty
  { name: 'Dunhill Red (pack)', category: 'Cigarettes', price: '14.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Djarum Black Clove Cigars 12pk', category: 'Cigarettes', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Roll-Your-Own
  { name: 'Bugler Turkish RYO Tobacco 6oz', category: 'Cigarettes', price: '16.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Top Original RYO Tobacco 6oz', category: 'Cigarettes', price: '16.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // === Cigars & Cigarillos (Restricted) ===
  // Swisher Sweets
  { name: 'Swisher Sweets Original Cigarillo 2pk', category: 'Cigars', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Swisher Sweets Grape Cigarillo 2pk', category: 'Cigars', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Swisher Sweets Strawberry Cigarillo 2pk', category: 'Cigars', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Swisher Sweets Peach Cigarillo 2pk', category: 'Cigars', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Swisher Sweets Blueberry Cigarillo 2pk', category: 'Cigars', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Swisher Sweets Watermelon Cigarillo 2pk', category: 'Cigars', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Swisher Sweets Tropical Fusion Cigarillo 2pk', category: 'Cigars', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Swisher Sweets Wild Rush Cigarillo 2pk', category: 'Cigars', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Swisher Sweets White Grape Cigarillo 2pk', category: 'Cigars', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Swisher Sweets Diamond Cigarillo 2pk', category: 'Cigars', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Swisher Sweets Banana Smash Cigarillo 2pk', category: 'Cigars', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Swisher Sweets Honey Sport Cigarillo 2pk', category: 'Cigars', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Backwoods
  { name: 'Backwoods Original 5pk', category: 'Cigars', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Backwoods Honey Berry 5pk', category: 'Cigars', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Backwoods Honey Bourbon 5pk', category: 'Cigars', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Backwoods Sweet Aromatic 5pk', category: 'Cigars', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Backwoods Dark Stout 5pk', category: 'Cigars', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Backwoods Black Russian 5pk', category: 'Cigars', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Backwoods Wild N Mild 5pk', category: 'Cigars', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Backwoods Grape 5pk', category: 'Cigars', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Backwoods Honey 5pk', category: 'Cigars', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Black & Mild
  { name: 'Black & Mild Classic 5pk', category: 'Cigars', price: '5.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Black & Mild Jazz 5pk', category: 'Cigars', price: '5.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Black & Mild Apple 5pk', category: 'Cigars', price: '5.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Black & Mild Wine 5pk', category: 'Cigars', price: '5.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Black & Mild Cream 5pk', category: 'Cigars', price: '5.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Black & Mild Sweets 5pk', category: 'Cigars', price: '5.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Black & Mild Cherry 5pk', category: 'Cigars', price: '5.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Black & Mild Royale 5pk', category: 'Cigars', price: '5.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Black & Mild Shorts Original 5pk', category: 'Cigars', price: '5.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // White Owl
  { name: 'White Owl Grape 2pk', category: 'Cigars', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'White Owl Strawberry 2pk', category: 'Cigars', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'White Owl White Grape 2pk', category: 'Cigars', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'White Owl Green Sweets 2pk', category: 'Cigars', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'White Owl Peach 2pk', category: 'Cigars', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'White Owl Sour Apple 2pk', category: 'Cigars', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'White Owl Tropical Twist 2pk', category: 'Cigars', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'White Owl Mango 2pk', category: 'Cigars', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Dutch Masters
  { name: 'Dutch Masters Original 2pk', category: 'Cigars', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Dutch Masters Honey 2pk', category: 'Cigars', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Dutch Masters Vanilla Smooth 2pk', category: 'Cigars', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Dutch Masters Rum Fusion 2pk', category: 'Cigars', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Dutch Masters Palma 2pk', category: 'Cigars', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Dutch Masters Berry Fusion 2pk', category: 'Cigars', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Dutch Masters Atomic Fusion 2pk', category: 'Cigars', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Phillies
  { name: 'Phillies Original Blunt 2pk', category: 'Cigars', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Phillies Grape Blunt 2pk', category: 'Cigars', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Phillies Strawberry Blunt 2pk', category: 'Cigars', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Phillies Sweet Blunt 2pk', category: 'Cigars', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Phillies Cherry Blunt 2pk', category: 'Cigars', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Phillies Chocolate Blunt 2pk', category: 'Cigars', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Garcia y Vega Game
  { name: 'Game Original Cigarillo 2pk', category: 'Cigars', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Game Honey Cigarillo 2pk', category: 'Cigars', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Game Grape Cigarillo 2pk', category: 'Cigars', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Game Silver Cigarillo 2pk', category: 'Cigars', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Game Red Sweet Cigarillo 2pk', category: 'Cigars', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Optimo
  { name: 'Optimo Grape Cigarillo 2pk', category: 'Cigars', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Optimo Sweet Cigarillo 2pk', category: 'Cigars', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Optimo Original Cigarillo 2pk', category: 'Cigars', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Middleton / Cheyenne / Prime Time
  { name: "Middleton's Cherry Blend Pipe Tobacco 1.5oz", category: 'Cigars', price: '7.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Cheyenne Grape Filtered Cigars 20ct', category: 'Cigars', price: '4.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Prime Time Original Little Cigars 20ct', category: 'Cigars', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Djarum Bali Hai Clove Cigars 12pk', category: 'Cigars', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Premium singles
  { name: 'Romeo y Julieta 1875 Bully Single', category: 'Cigars', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Montecristo White Toro Single', category: 'Cigars', price: '13.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Arturo Fuente Hemingway Short Story Single', category: 'Cigars', price: '11.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Macanudo Café Hyde Park Single', category: 'Cigars', price: '9.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Cohiba Red Dot Robusto Single', category: 'Cigars', price: '14.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Punch Rare Corojo Champion Single', category: 'Cigars', price: '7.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Ashton Classic Churchill Single', category: 'Cigars', price: '14.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Padron 2000 Natural Single', category: 'Cigars', price: '7.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Oliva Serie V Torpedo Single', category: 'Cigars', price: '12.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Rocky Patel Vintage 1990 Toro Single', category: 'Cigars', price: '10.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // === Smokeless Tobacco (Restricted) ===
  // Copenhagen
  { name: 'Copenhagen Original Long Cut 1.2oz', category: 'Smokeless', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Copenhagen Original Fine Cut 1.2oz', category: 'Smokeless', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Copenhagen Wintergreen Long Cut 1.2oz', category: 'Smokeless', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Copenhagen Southern Blend Long Cut 1.2oz', category: 'Smokeless', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Copenhagen Straight Long Cut 1.2oz', category: 'Smokeless', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Copenhagen Extra Long Cut Natural 1.2oz', category: 'Smokeless', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Grizzly
  { name: 'Grizzly Wintergreen Long Cut 1.2oz', category: 'Smokeless', price: '6.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Grizzly Straight Long Cut 1.2oz', category: 'Smokeless', price: '6.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Grizzly Mint Long Cut 1.2oz', category: 'Smokeless', price: '6.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Grizzly Dark Wintergreen Long Cut 1.2oz', category: 'Smokeless', price: '6.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Grizzly Wintergreen Pouches 0.82oz', category: 'Smokeless', price: '6.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Skoal
  { name: 'Skoal Mint Long Cut 1.2oz', category: 'Smokeless', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Skoal Wintergreen Long Cut 1.2oz', category: 'Smokeless', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Skoal Straight Long Cut 1.2oz', category: 'Smokeless', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Skoal Classic Long Cut 1.2oz', category: 'Smokeless', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Skoal Berry Long Cut 1.2oz', category: 'Smokeless', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Skoal Wintergreen Pouches 0.82oz', category: 'Smokeless', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // Misc smokeless
  { name: 'Red Man Original Chewing Tobacco 3oz', category: 'Smokeless', price: '5.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Stoker\'s Long Cut Original 12oz', category: 'Smokeless', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Kodiak Wintergreen Long Cut 1.2oz', category: 'Smokeless', price: '6.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Levi Garrett Loose Leaf Chew 3oz', category: 'Smokeless', price: '5.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // General
  { name: 'AA Batteries 4pk Duracell', category: 'Electronics', price: '7.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'AAA Batteries 4pk Duracell', category: 'Electronics', price: '7.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'USB-A to Lightning Cable 3ft', category: 'Electronics', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'USB-C Charging Cable 3ft', category: 'Electronics', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Earbuds – Wired 3.5mm', category: 'Electronics', price: '9.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Hand Sanitizer 2oz Purell', category: 'General', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Tylenol Travel Pack 2ct', category: 'General', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Condom – Lifestyle 1pk', category: 'General', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Lighter – BIC', category: 'General', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Ziplock Bags Sandwich 10ct', category: 'General', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Condom – Trojan Magnum 1pk', category: 'General', price: '4.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
]
