export interface CatalogItem {
  name: string
  category: string
  price: string
  nighttimeAvailable: string
  restrictedFlag: string
  imageUrl?: string
}

export const PRESET_CATALOG: CatalogItem[] = [
  // Energy & Drinks
  { name: 'Red Bull 8.4oz', category: 'Energy Drinks', price: '4.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Red Bull Sugar Free 8.4oz', category: 'Energy Drinks', price: '4.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Monster Energy Original 16oz', category: 'Energy Drinks', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Monster Zero Ultra 16oz', category: 'Energy Drinks', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Celsius Sparkling Orange 12oz', category: 'Energy Drinks', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: '5-hour ENERGY Extra Strength', category: 'Energy Drinks', price: '4.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Gatorade Fruit Punch 32oz', category: 'Sports Drinks', price: '3.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Gatorade Lemon-Lime 32oz', category: 'Sports Drinks', price: '3.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Powerade Mountain Berry Blast 32oz', category: 'Sports Drinks', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Liquid IV Hydration Multiplier', category: 'Sports Drinks', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Smartwater 1L', category: 'Water', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'FIJI Water 1L', category: 'Water', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Evian Natural Spring Water 1L', category: 'Water', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Essentia 9.5 pH Water 1L', category: 'Water', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Coca-Cola 20oz', category: 'Soft Drinks', price: '2.79', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Diet Coke 20oz', category: 'Soft Drinks', price: '2.79', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Sprite 20oz', category: 'Soft Drinks', price: '2.79', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Dr Pepper 20oz', category: 'Soft Drinks', price: '2.79', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Mountain Dew 20oz', category: 'Soft Drinks', price: '2.79', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Arizona Green Tea 23oz', category: 'Soft Drinks', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Lipton Brisk Iced Tea 20oz', category: 'Soft Drinks', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Tropicana Orange Juice 10oz', category: 'Juice', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Minute Maid Lemonade 20oz', category: 'Juice', price: '2.79', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Starbucks Frappuccino Mocha 13.7oz', category: 'Coffee', price: '4.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Starbucks Double Shot Espresso 6.5oz', category: 'Coffee', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Monster Java Mean Bean 15oz', category: 'Coffee', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  // Snacks
  { name: 'Doritos Nacho Cheese 2.75oz', category: 'Chips', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Doritos Cool Ranch 2.75oz', category: 'Chips', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: "Lay's Classic 2.625oz", category: 'Chips', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: "Lay's Sour Cream & Onion 2.625oz", category: 'Chips', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Cheetos Crunchy 2.375oz', category: 'Chips', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Fritos Original 2oz', category: 'Chips', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Pringles Original 2.5oz', category: 'Chips', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Takis Fuego 3.2oz', category: 'Chips', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Kettle Brand Sea Salt 2oz', category: 'Chips', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Snickers 1.86oz', category: 'Candy', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Snickers King Size 3.29oz', category: 'Candy', price: '3.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: "Reese's Peanut Butter Cups 1.5oz", category: 'Candy', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: "Reese's King Size 2.8oz", category: 'Candy', price: '3.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Kit Kat 1.5oz', category: 'Candy', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Twix 1.79oz', category: 'Candy', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'M&Ms Peanut 1.74oz', category: 'Candy', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Skittles Original 2.17oz', category: 'Candy', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Starburst Original 2.07oz', category: 'Candy', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Haribo Gold-Bears 4oz', category: 'Candy', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Airheads Variety 3.3oz', category: 'Candy', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Nature Valley Oats & Honey Bar', category: 'Bars', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Clif Bar Chocolate Chip', category: 'Bars', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Kind Dark Chocolate Nuts & Sea Salt', category: 'Bars', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'RXBar Chocolate Sea Salt', category: 'Bars', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Planters Dry Roasted Peanuts 1.75oz', category: 'Nuts', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Planters Mixed Nuts 1.75oz', category: 'Nuts', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Sunflower Seeds David Original 1.75oz', category: 'Nuts', price: '2.29', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  // Food
  { name: 'Slim Jim Original 0.97oz', category: 'Meat Snacks', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Slim Jim Giant 1.94oz', category: 'Meat Snacks', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Jack Links Beef Jerky 1.25oz', category: 'Meat Snacks', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Old Wisconsin Turkey Stick', category: 'Meat Snacks', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Hot Dog – Roller Grill', category: 'Hot Food', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Cheeseburger – Heated', category: 'Hot Food', price: '4.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Taquito – Chicken', category: 'Hot Food', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Taquito – Beef', category: 'Hot Food', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: "Chester's Fries 1.75oz", category: 'Hot Food', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Pop-Tarts Frosted Strawberry 2pk', category: 'Pastry', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Honey Bun', category: 'Pastry', price: '1.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Donettes Powdered Mini Donuts 3oz', category: 'Pastry', price: '2.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  // Health & Personal Care
  { name: 'Advil Ibuprofen 200mg 10ct', category: 'Pain Relief', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Tylenol Extra Strength 10ct', category: 'Pain Relief', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Aleve 220mg 8ct', category: 'Pain Relief', price: '6.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Pepto-Bismol Chewable 4ct', category: 'Stomach', price: '5.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Tums Ultra Strength 12ct', category: 'Stomach', price: '4.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Tylenol PM 10ct', category: 'Sleep', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'ZzzQuil Nighttime Sleep Aid 12ct', category: 'Sleep', price: '9.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Unisom SleepTabs 8ct', category: 'Sleep', price: '8.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Trojan ENZ Condoms 3pk', category: 'Personal Care', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Trojan Ultra Thin 3pk', category: 'Personal Care', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Durex Extra Sensitive 3pk', category: 'Personal Care', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Chapstick Original', category: 'Personal Care', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: "Burt's Bees Lip Balm", category: 'Personal Care', price: '4.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Visine Original Eye Drops 0.5oz', category: 'Personal Care', price: '7.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Listerine PocketPaks Strips 24ct', category: 'Personal Care', price: '4.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Colgate Wisp Disposable Toothbrush', category: 'Personal Care', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  // Tobacco (Restricted) — will be greatly expanded in follow-up commits
  { name: 'Marlboro Red (pack)', category: 'Tobacco', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Marlboro Light (pack)', category: 'Tobacco', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Newport Menthol (pack)', category: 'Tobacco', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Camel Blue (pack)', category: 'Tobacco', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Swisher Sweets Cigarillo 2pk', category: 'Tobacco', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Backwoods Original 5pk', category: 'Tobacco', price: '8.99', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  // General
  { name: 'AA Batteries 4pk Duracell', category: 'Electronics', price: '7.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'AAA Batteries 4pk Duracell', category: 'Electronics', price: '7.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'USB-A to Lightning Cable 3ft', category: 'Electronics', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'USB-C Charging Cable 3ft', category: 'Electronics', price: '12.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Earbuds – Wired 3.5mm', category: 'Electronics', price: '9.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Hand Sanitizer 2oz Purell', category: 'General', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Tylenol Travel Pack 2ct', category: 'General', price: '2.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Condom – Lifestyle 1pk', category: 'General', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Lighter – BIC', category: 'General', price: '3.49', nighttimeAvailable: 'true', restrictedFlag: 'true' },
  { name: 'Ziplock Bags Sandwich 10ct', category: 'General', price: '3.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
  { name: 'Condom – Trojan Magnum 1pk', category: 'General', price: '4.99', nighttimeAvailable: 'true', restrictedFlag: 'false' },
]
