import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()
const p = (name: string, category: string, price: number, restricted = false) => ({
  name, category, price, nighttimeAvailable: true, restrictedFlag: restricted,
})

const catalog = [
  // WATER
  p('Smartwater 1L', 'Water', 349),
  p('FIJI Water 1L', 'Water', 399),
  p('Evian Natural Spring Water 1L', 'Water', 399),
  p('Essentia 9.5pH Water 1L', 'Water', 349),
  p('Aquafina 20oz', 'Water', 229),
  p('Dasani 20oz', 'Water', 229),
  p('Deer Park Natural Spring 1L', 'Water', 249),
  p('Poland Spring 1L', 'Water', 249),
  p('Sparkling Ice Black Raspberry 17oz', 'Water', 229),
  p('LaCroix Sparkling Water Lime 12oz', 'Water', 249),
  // SOFT DRINKS
  p('Coca-Cola 20oz', 'Soft Drinks', 279),
  p('Coca-Cola Zero Sugar 20oz', 'Soft Drinks', 279),
  p('Diet Coke 20oz', 'Soft Drinks', 279),
  p('Pepsi 20oz', 'Soft Drinks', 279),
  p('Pepsi Zero Sugar 20oz', 'Soft Drinks', 279),
  p('Sprite 20oz', 'Soft Drinks', 279),
  p('Dr Pepper 20oz', 'Soft Drinks', 279),
  p('Mountain Dew 20oz', 'Soft Drinks', 279),
  p('Mountain Dew Code Red 20oz', 'Soft Drinks', 279),
  p('7UP 20oz', 'Soft Drinks', 249),
  p('Fanta Orange 20oz', 'Soft Drinks', 279),
  p("A&W Root Beer 20oz", 'Soft Drinks', 249),
  p('Orange Crush 20oz', 'Soft Drinks', 249),
  p("Barq's Root Beer 20oz", 'Soft Drinks', 249),
  p('Mello Yello 20oz', 'Soft Drinks', 249),
  // ENERGY DRINKS
  p('Red Bull 8.4oz', 'Energy Drinks', 449),
  p('Red Bull Sugar Free 8.4oz', 'Energy Drinks', 449),
  p('Red Bull 16oz', 'Energy Drinks', 599),
  p('Monster Energy Original 16oz', 'Energy Drinks', 399),
  p('Monster Zero Ultra 16oz', 'Energy Drinks', 399),
  p('Monster Ultra Sunrise 16oz', 'Energy Drinks', 399),
  p('Monster Ultra Watermelon 16oz', 'Energy Drinks', 399),
  p('Bang Energy Sour Heads 16oz', 'Energy Drinks', 349),
  p('Bang Energy Purple Haze 16oz', 'Energy Drinks', 349),
  p('Celsius Sparkling Orange 12oz', 'Energy Drinks', 399),
  p('Celsius Raspberry Acai 12oz', 'Energy Drinks', 399),
  p('Celsius Sparkling Watermelon 12oz', 'Energy Drinks', 399),
  p('Reign Total Body Fuel Melon 16oz', 'Energy Drinks', 349),
  p('Rockstar Original 16oz', 'Energy Drinks', 329),
  p('NOS High Performance 16oz', 'Energy Drinks', 329),
  p('5-Hour Energy Extra Strength', 'Energy Drinks', 499),
  p('5-Hour Energy Berry', 'Energy Drinks', 499),
  p('Alani Nu Cherry Slush 12oz', 'Energy Drinks', 399),
  p('Ghost Energy Sour Patch Kids 16oz', 'Energy Drinks', 399),
  p('C4 Smart Energy Cotton Candy 12oz', 'Energy Drinks', 299),
  // SPORTS DRINKS
  p('Gatorade Fruit Punch 32oz', 'Sports Drinks', 329),
  p('Gatorade Lemon-Lime 32oz', 'Sports Drinks', 329),
  p('Gatorade Cool Blue 32oz', 'Sports Drinks', 329),
  p('Gatorade Orange 32oz', 'Sports Drinks', 329),
  p('Gatorade G Zero Grape 28oz', 'Sports Drinks', 299),
  p('Powerade Mountain Berry Blast 32oz', 'Sports Drinks', 299),
  p('Powerade Fruit Punch 32oz', 'Sports Drinks', 299),
  p('BodyArmor Tropical Punch 16oz', 'Sports Drinks', 299),
  p('BodyArmor Strawberry Banana 28oz', 'Sports Drinks', 349),
  p('Liquid IV Hydration Multiplier 16oz', 'Sports Drinks', 349),
  // COFFEE & TEA
  p('Starbucks Frappuccino Mocha 13.7oz', 'Coffee & Tea', 449),
  p('Starbucks Frappuccino Vanilla 13.7oz', 'Coffee & Tea', 449),
  p('Starbucks Frappuccino Caramel 13.7oz', 'Coffee & Tea', 449),
  p('Starbucks Double Shot Espresso 6.5oz', 'Coffee & Tea', 399),
  p('Starbucks Cold Brew Black 11oz', 'Coffee & Tea', 499),
  p('Monster Java Mean Bean 15oz', 'Coffee & Tea', 399),
  p('Monster Java Loca Moca 15oz', 'Coffee & Tea', 399),
  p('AriZona Green Tea 23oz', 'Coffee & Tea', 199),
  p('AriZona Iced Tea Lemon 23oz', 'Coffee & Tea', 199),
  p('Lipton Brisk Iced Tea 20oz', 'Coffee & Tea', 229),
  p('Gold Peak Sweet Tea 18.5oz', 'Coffee & Tea', 249),
  p('Pure Leaf Sweet Tea 18.5oz', 'Coffee & Tea', 279),
  p('Snapple Peach Tea 16oz', 'Coffee & Tea', 249),
  p('Stok Cold Brew Coffee 13.7oz', 'Coffee & Tea', 449),
  // JUICE
  p('Tropicana Orange Juice 10oz', 'Juice', 349),
  p('Tropicana Apple Juice 10oz', 'Juice', 349),
  p('Minute Maid Lemonade 20oz', 'Juice', 279),
  p('Minute Maid Fruit Punch 20oz', 'Juice', 279),
  p('Ocean Spray Cranberry 10oz', 'Juice', 299),
  p('Naked Green Machine 15.2oz', 'Juice', 499),
  p('Naked Mighty Mango 15.2oz', 'Juice', 499),
  p('V8 Original Vegetable Juice 11.5oz', 'Juice', 249),
  p("Welch's Strawberry 10oz", 'Juice', 299),
  // MILK
  p('Whole Milk 1pt', 'Milk', 299),
  p('2% Milk 1pt', 'Milk', 299),
  p('Chocolate Milk 14oz', 'Milk', 299),
  p('Fairlife Chocolate Milk 14oz', 'Milk', 399),
  // BEER
  p('Bud Light 25oz Can', 'Beer', 449, true),
  p('Budweiser 25oz Can', 'Beer', 449, true),
  p('Coors Light 25oz Can', 'Beer', 449, true),
  p('Miller Lite 25oz Can', 'Beer', 449, true),
  p('Michelob Ultra 25oz Can', 'Beer', 499, true),
  p('Corona Extra 24oz', 'Beer', 499, true),
  p('Modelo Especial 24oz', 'Beer', 499, true),
  p('Heineken 22oz', 'Beer', 499, true),
  p('Stella Artois 22oz', 'Beer', 499, true),
  p('Blue Moon Belgian White 22oz', 'Beer', 499, true),
  p('Guinness Draught 14.9oz Can', 'Beer', 549, true),
  p('Dos Equis Lager 24oz', 'Beer', 499, true),
  p('Samuel Adams Boston Lager 22oz', 'Beer', 499, true),
  p('White Claw Hard Seltzer Black Cherry 19.2oz', 'Beer', 449, true),
  p('Truly Wild Berry Hard Seltzer 19.2oz', 'Beer', 449, true),
  p('High Noon Watermelon Vodka Soda 12oz', 'Beer', 449, true),
  p('Twisted Tea Original 24oz', 'Beer', 449, true),
  p("Mike's Hard Lemonade 24oz", 'Beer', 449, true),
  p('Bud Light Lime 16oz', 'Beer', 349, true),
  p('Natural Light 25oz', 'Beer', 299, true),
  // WINE
  p('Barefoot Pinot Grigio 187ml', 'Wine', 499, true),
  p('Barefoot Cabernet Sauvignon 187ml', 'Wine', 499, true),
  p('Sutter Home Chardonnay 187ml', 'Wine', 499, true),
  p('Josh Cellars Cabernet 187ml', 'Wine', 599, true),
  p('Kim Crawford Sauvignon Blanc 187ml', 'Wine', 699, true),
  // SPIRITS
  p("Jack Daniel's Tennessee Whiskey 50ml", 'Spirits', 499, true),
  p('Jim Beam Bourbon 50ml', 'Spirits', 399, true),
  p('Fireball Cinnamon Whisky 50ml', 'Spirits', 299, true),
  p("Tito's Handmade Vodka 50ml", 'Spirits', 499, true),
  p('Smirnoff Vodka 50ml', 'Spirits', 349, true),
  p('Captain Morgan Spiced Rum 50ml', 'Spirits', 349, true),
  p('Jose Cuervo Gold Tequila 50ml', 'Spirits', 399, true),
  p('Hennessy VS Cognac 50ml', 'Spirits', 699, true),
  p('Crown Royal Whisky 50ml', 'Spirits', 499, true),
  p('Patron Silver Tequila 50ml', 'Spirits', 599, true),
  // CHIPS
  p('Doritos Nacho Cheese 2.75oz', 'Chips', 249),
  p('Doritos Cool Ranch 2.75oz', 'Chips', 249),
  p("Doritos Flamin' Hot 2.75oz", 'Chips', 249),
  p('Doritos Spicy Nacho 2.75oz', 'Chips', 249),
  p("Lay's Classic 2.625oz", 'Chips', 249),
  p("Lay's Sour Cream & Onion 2.625oz", 'Chips', 249),
  p("Lay's Barbecue 2.625oz", 'Chips', 249),
  p("Lay's Flamin' Hot 2.625oz", 'Chips', 249),
  p('Cheetos Crunchy 2.375oz', 'Chips', 249),
  p('Cheetos Puffs 2.375oz', 'Chips', 249),
  p("Flamin' Hot Cheetos 2.375oz", 'Chips', 249),
  p('Fritos Original 2oz', 'Chips', 229),
  p('Fritos Chili Cheese 2oz', 'Chips', 229),
  p('Pringles Original 2.5oz', 'Chips', 299),
  p('Pringles Sour Cream & Onion 2.5oz', 'Chips', 299),
  p('Pringles Cheddar 2.5oz', 'Chips', 299),
  p('Takis Fuego 3.2oz', 'Chips', 299),
  p('Takis Blue Heat 3.2oz', 'Chips', 299),
  p('Kettle Brand Sea Salt 2oz', 'Chips', 299),
  p('Ruffles Original 2.5oz', 'Chips', 249),
  p('SunChips Garden Salsa 1.5oz', 'Chips', 229),
  p('Funyuns Onion Rings 2.125oz', 'Chips', 249),
  p('Bugles Original 1.5oz', 'Chips', 229),
  p('PopCorners White Cheddar 1oz', 'Chips', 249),
  p('Cape Cod Sea Salt 2oz', 'Chips', 299),
  // CRACKERS
  p('Ritz Crackers 1.35oz', 'Crackers', 199),
  p('Goldfish Cheddar 1.5oz', 'Crackers', 199),
  p('Triscuit Original 2oz', 'Crackers', 229),
  p('Wheat Thins Original 1.75oz', 'Crackers', 229),
  p('Club Crackers 1.4oz', 'Crackers', 199),
  // NUTS & SEEDS
  p('Planters Dry Roasted Peanuts 1.75oz', 'Nuts & Seeds', 249),
  p('Planters Mixed Nuts 1.75oz', 'Nuts & Seeds', 299),
  p('Blue Diamond Almonds Roasted Salted 1.5oz', 'Nuts & Seeds', 299),
  p('Emerald Cashews 1.5oz', 'Nuts & Seeds', 349),
  p('David Original Sunflower Seeds 1.75oz', 'Nuts & Seeds', 229),
  p('David Ranch Sunflower Seeds 1.75oz', 'Nuts & Seeds', 229),
  p('Wonderful Pistachios 1.5oz', 'Nuts & Seeds', 349),
  p('Chili Lime Pumpkin Seeds 1.5oz', 'Nuts & Seeds', 249),
  // POPCORN
  p('Smartfood White Cheddar Popcorn 2oz', 'Popcorn', 299),
  p('Boom Chicka Pop Sea Salt 1oz', 'Popcorn', 249),
  p('SkinnyPop Original 1oz', 'Popcorn', 229),
  p("Orville Redenbacher's Kettle Corn 2.8oz", 'Popcorn', 249),
  // PRETZELS
  p("Snyder's Pretzel Pieces 2.25oz", 'Pretzels', 229),
  p('Rold Gold Classic Thins 1.5oz', 'Pretzels', 229),
  p("Dot's Homestyle Pretzels 1.5oz", 'Pretzels', 249),
  // MEAT SNACKS
  p('Slim Jim Original 0.97oz', 'Meat Snacks', 199),
  p('Slim Jim Giant 1.94oz', 'Meat Snacks', 299),
  p("Jack Link's Beef Jerky Original 1.25oz", 'Meat Snacks', 399),
  p("Jack Link's Beef Jerky Teriyaki 1.25oz", 'Meat Snacks', 399),
  p("Jack Link's Beef Jerky Peppered 1.25oz", 'Meat Snacks', 399),
  p('Krave Black Cherry BBQ Beef Jerky 1oz', 'Meat Snacks', 449),
  p('Old Wisconsin Turkey Stick', 'Meat Snacks', 249),
  p('Chomps Grass-Fed Beef Stick 1.15oz', 'Meat Snacks', 399),
  p('Epic Provisions Beef Jerky Bar 1oz', 'Meat Snacks', 399),
  p("Mac's Original Pork Rinds 1.75oz", 'Meat Snacks', 229),
  // CHOCOLATE
  p('Snickers King Size 3.29oz', 'Chocolate', 329),
  p('Twix King Size 3.02oz', 'Chocolate', 329),
  p('Kit Kat King Size 3oz', 'Chocolate', 329),
  p("Reese's Peanut Butter Cups King Size 2.8oz", 'Chocolate', 329),
  p('M&Ms Peanut 1.74oz', 'Chocolate', 229),
  p('M&Ms Milk Chocolate 1.69oz', 'Chocolate', 229),
  p('M&Ms Peanut Butter 1.63oz', 'Chocolate', 229),
  p('Milky Way King Size 3.63oz', 'Chocolate', 329),
  p('3 Musketeers King Size 3.28oz', 'Chocolate', 329),
  p('Butterfinger King Size 3.7oz', 'Chocolate', 329),
  p('Baby Ruth King Size 3.7oz', 'Chocolate', 329),
  p("Hershey's Milk Chocolate 1.55oz", 'Chocolate', 229),
  p("Hershey's Cookies 'n' Creme 1.55oz", 'Chocolate', 229),
  p('Almond Joy 1.76oz', 'Chocolate', 229),
  p('York Peppermint Pattie King Size 2.84oz', 'Chocolate', 329),
  p('Crunch Bar 1.55oz', 'Chocolate', 229),
  p('PayDay Peanut Caramel 1.85oz', 'Chocolate', 229),
  p('Whatchamacallit 1.6oz', 'Chocolate', 229),
  p("Reese's Pieces 1.53oz", 'Chocolate', 229),
  p('Kit Kat Duos 1.5oz', 'Chocolate', 229),
  // CANDY
  p('Haribo Gold-Bears 4oz', 'Candy', 299),
  p('Trolli Sour Brite Crawlers 3oz', 'Candy', 299),
  p('Swedish Fish 3.1oz', 'Candy', 299),
  p('Sour Patch Kids 2oz', 'Candy', 249),
  p('Sour Patch Kids Watermelon 2oz', 'Candy', 249),
  p('Starburst Original 2.07oz', 'Candy', 229),
  p('Skittles Original 2.17oz', 'Candy', 229),
  p('Skittles Wild Berry 2.17oz', 'Candy', 229),
  p('Airheads Variety 3.3oz', 'Candy', 249),
  p('Nerds Rope 1.5oz', 'Candy', 229),
  p('Twizzlers Strawberry 5oz', 'Candy', 299),
  p('Jolly Rancher Assorted 7oz', 'Candy', 399),
  p("Werther's Original 2.65oz", 'Candy', 249),
  p('Peach Rings 2.5oz', 'Candy', 249),
  p('Ring Pop 1pk', 'Candy', 149),
  // GUM & MINTS
  p('Extra Spearmint Gum 35-stick', 'Gum & Mints', 249),
  p('Extra Peppermint Gum 35-stick', 'Gum & Mints', 249),
  p('Orbit Spearmint 14-piece', 'Gum & Mints', 199),
  p('Trident Spearmint 18-piece', 'Gum & Mints', 199),
  p('5 Gum Spearmint Rain 15-stick', 'Gum & Mints', 249),
  p('Altoids Peppermint 1.76oz', 'Gum & Mints', 349),
  p('Tic Tac Orange 1oz', 'Gum & Mints', 199),
  p('Ice Breakers Peppermint 1.5oz', 'Gum & Mints', 249),
  // BARS
  p('Clif Bar Chocolate Chip 2.4oz', 'Bars', 349),
  p('Clif Bar Crunchy Peanut Butter 2.4oz', 'Bars', 349),
  p('Kind Dark Chocolate Nuts & Sea Salt 1.4oz', 'Bars', 349),
  p('Kind Caramel Almond & Sea Salt 1.4oz', 'Bars', 349),
  p('RXBar Chocolate Sea Salt 1.83oz', 'Bars', 399),
  p('RXBar Blueberry 1.83oz', 'Bars', 399),
  p('Quest Protein Bar Chocolate Chip Cookie Dough', 'Bars', 399),
  p('ONE Protein Bar Birthday Cake', 'Bars', 349),
  p('Nature Valley Oats & Honey Bar 1.5oz', 'Bars', 249),
  p('Larabar Apple Pie 1.8oz', 'Bars', 299),
  p("Kellogg's Special K Protein Bar", 'Bars', 249),
  p('Fiber One Oats & Chocolate 1.4oz', 'Bars', 199),
  // PASTRY
  p('Honey Bun', 'Pastry', 199),
  p('Pop-Tarts Frosted Strawberry 2-pk', 'Pastry', 249),
  p('Pop-Tarts Brown Sugar Cinnamon 2-pk', 'Pastry', 249),
  p('Donettes Powdered Mini Donuts 3oz', 'Pastry', 249),
  p('Little Debbie Swiss Rolls 2.7oz', 'Pastry', 229),
  p('Little Debbie Oatmeal Creme Pies 2.7oz', 'Pastry', 229),
  p('Hostess Twinkies 2-pk 2.7oz', 'Pastry', 249),
  p('Hostess Ding Dongs 2-pk 2.89oz', 'Pastry', 249),
  p('Tastykake Butterscotch Krimpets', 'Pastry', 199),
  p("Drake's Coffee Cakes 2-pk", 'Pastry', 199),
  // HOT FOOD
  p('Hot Dog Roller Grill', 'Hot Food', 349),
  p('Corn Dog', 'Hot Food', 349),
  p('Taquito Chicken', 'Hot Food', 249),
  p('Taquito Beef', 'Hot Food', 249),
  p('Cheeseburger Heated', 'Hot Food', 499),
  p('Breakfast Sandwich Egg & Cheese', 'Hot Food', 449),
  p('Pizza Slice Pepperoni', 'Hot Food', 399),
  p('Pizza Slice Cheese', 'Hot Food', 349),
  p('Bean & Cheese Burrito', 'Hot Food', 399),
  p('Beef Burrito', 'Hot Food', 399),
  p('Sausage Roller Grill', 'Hot Food', 349),
  p('Jalapeno Cheddar Bite', 'Hot Food', 299),
  p('Mac & Cheese Bite 3pk', 'Hot Food', 299),
  p('Mozzarella Sticks 3pk', 'Hot Food', 349),
  p("Chester's Fries 1.75oz", 'Hot Food', 199),
  // ICE CREAM
  p("Ben & Jerry's Chocolate Chip Cookie Dough 1pt", 'Ice Cream', 799),
  p("Ben & Jerry's Half Baked 1pt", 'Ice Cream', 799),
  p('Haagen-Dazs Vanilla 14oz', 'Ice Cream', 699),
  p('Magnum Double Caramel Bar', 'Ice Cream', 499),
  p('Drumstick Classic Vanilla', 'Ice Cream', 349),
  p('Klondike Original Vanilla Bar', 'Ice Cream', 349),
  p("Klondike Reese's Bar", 'Ice Cream', 349),
  p('Good Humor Strawberry Shortcake Bar', 'Ice Cream', 349),
  p('Chipwich Vanilla', 'Ice Cream', 449),
  p('Popsicle Cherry Bomb', 'Ice Cream', 299),
  // DAIRY
  p('String Cheese Sargento 0.75oz', 'Dairy', 199),
  p('Babybel Mini Cheese 0.75oz', 'Dairy', 199),
  p('Yoplait Original Strawberry Yogurt 6oz', 'Dairy', 199),
  p('Chobani Strawberry Greek Yogurt 5.3oz', 'Dairy', 249),
  p('Hard Boiled Eggs 2-pk', 'Dairy', 249),
  p('Fairlife Core Power Chocolate Shake 14oz', 'Dairy', 449),
  p('Dannon Activia Vanilla 4oz', 'Dairy', 199),
  p('Laughing Cow Cheese Wedge 1oz', 'Dairy', 199),
  p('GoGo Squeeze Apple Applesauce 3.2oz', 'Dairy', 199),
  p('KeVita Lemon Cayenne Kombucha 15.2oz', 'Dairy', 399),
  // PAIN RELIEF
  p('Advil Ibuprofen 200mg 10ct', 'Pain Relief', 699),
  p('Tylenol Extra Strength 500mg 10ct', 'Pain Relief', 699),
  p('Aleve 220mg 8ct', 'Pain Relief', 699),
  p('Bayer Aspirin 325mg 12ct', 'Pain Relief', 499),
  p('Excedrin Migraine 10ct', 'Pain Relief', 699),
  p('Motrin IB 200mg 8ct', 'Pain Relief', 599),
  p("Goody's Headache Powder 6ct", 'Pain Relief', 449),
  p('Generic Ibuprofen 200mg 10ct', 'Pain Relief', 499),
  p('Bayer Aspirin Regimen 81mg 32ct', 'Pain Relief', 699),
  p('BC Powder Headache Relief 6ct', 'Pain Relief', 449),
  // DIGESTIVE
  p('Pepto-Bismol Chewable Tablets 4ct', 'Digestive', 599),
  p('Tums Ultra Strength 750mg 12ct', 'Digestive', 499),
  p('Imodium A-D Caplets 6ct', 'Digestive', 799),
  p('Gas-X Extra Strength 4ct', 'Digestive', 599),
  p('Maalox Quick Dissolve 4ct', 'Digestive', 499),
  // SLEEP & ALLERGY
  p('ZzzQuil Nighttime Sleep Aid 12ct', 'Sleep & Allergy', 999),
  p('Tylenol PM Extra Strength 10ct', 'Sleep & Allergy', 899),
  p('Unisom SleepTabs Doxylamine 8ct', 'Sleep & Allergy', 849),
  p('Melatonin 5mg 10ct', 'Sleep & Allergy', 699),
  p('Benadryl Allergy 25mg 10ct', 'Sleep & Allergy', 899),
  p('Claritin Non-Drowsy Loratadine 5ct', 'Sleep & Allergy', 899),
  p('Zyrtec Allergy Cetirizine 5ct', 'Sleep & Allergy', 899),
  p('DayQuil Cold & Flu LiquiCaps 8ct', 'Sleep & Allergy', 999),
  p('NyQuil Cold & Flu 12ct', 'Sleep & Allergy', 999),
  p('Sudafed PE Nasal Decongestant 18ct', 'Sleep & Allergy', 799),
  // FIRST AID
  p('Band-Aid Flexible Fabric 10ct', 'First Aid', 599),
  p('Neosporin Original Ointment 0.5oz', 'First Aid', 699),
  p('Hydrogen Peroxide 3% 8oz', 'First Aid', 349),
  p('Sterile Gauze Pads 2in 4ct', 'First Aid', 399),
  // PERSONAL CARE
  p('ChapStick Original', 'Personal Care', 349),
  p("Burt's Bees Lip Balm", 'Personal Care', 449),
  p('Listerine PocketPaks Strips 24ct', 'Personal Care', 499),
  p('Colgate Wisp Disposable Toothbrush 4pk', 'Personal Care', 349),
  p('Oral-B Travel Toothbrush', 'Personal Care', 299),
  p('Scope Travel Mouthwash 1.5oz', 'Personal Care', 249),
  p('Purell Advanced Hand Sanitizer 2oz', 'Personal Care', 399),
  p('Wet Ones Antibacterial Wipes 20ct', 'Personal Care', 399),
  p('Secret Invisible Solid Travel 0.5oz', 'Personal Care', 299),
  p('Old Spice Fresh Antiperspirant Travel', 'Personal Care', 299),
  p('Dove Nourishing Body Lotion Travel 1oz', 'Personal Care', 299),
  p('Neutrogena Ultra Sheer Sunscreen SPF50 1oz', 'Personal Care', 699),
  p('Trojan ENZ Condoms 3pk', 'Personal Care', 899),
  p('Trojan Ultra Thin Condoms 3pk', 'Personal Care', 899),
  p('Magnum Premium Condoms 3pk', 'Personal Care', 999),
  p('Durex Extra Sensitive Condoms 3pk', 'Personal Care', 899),
  p('Plan B One-Step Emergency Contraceptive', 'Personal Care', 4999),
  p('First Response Pregnancy Test 1pk', 'Personal Care', 1499),
  p('Always Radiant Maxi Pads 3ct', 'Personal Care', 299),
  p('Tampax Pearl Regular 3ct', 'Personal Care', 299),
  p('Visine Original Redness Eye Drops 0.5oz', 'Personal Care', 799),
  p('Systane Ultra Lubricant Eye Drops 0.33oz', 'Personal Care', 899),
  p('Gillette Good News Razors 2pk', 'Personal Care', 799),
  p('Venus Simply Disposable Razor 2pk', 'Personal Care', 799),
  p('Barbasol Original Shave Cream 2oz', 'Personal Care', 199),
  // TOBACCO
  p('Marlboro Red (pack)', 'Tobacco', 1299, true),
  p('Marlboro Light (pack)', 'Tobacco', 1299, true),
  p('Marlboro Menthol (pack)', 'Tobacco', 1299, true),
  p('Marlboro Gold (pack)', 'Tobacco', 1299, true),
  p('Newport Menthol (pack)', 'Tobacco', 1299, true),
  p('Newport (pack)', 'Tobacco', 1299, true),
  p('Camel Blue (pack)', 'Tobacco', 1299, true),
  p('Camel Turkish Gold (pack)', 'Tobacco', 1299, true),
  p('Camel Crush (pack)', 'Tobacco', 1299, true),
  p('American Spirit Yellow (pack)', 'Tobacco', 1499, true),
  p('American Spirit Blue (pack)', 'Tobacco', 1499, true),
  p('Winston Red (pack)', 'Tobacco', 1099, true),
  p('Pall Mall Menthol 100s (pack)', 'Tobacco', 1099, true),
  p('Swisher Sweets Cigarillo 2pk', 'Tobacco', 399, true),
  p('Black & Mild Jazz 5pk', 'Tobacco', 899, true),
  p('Backwoods Original 5pk', 'Tobacco', 899, true),
  p('Backwoods Honey Bourbon 5pk', 'Tobacco', 899, true),
  p('Phillies Blunt Cigarillo 2pk', 'Tobacco', 349, true),
  p('Grizzly Wintergreen Long Cut Snuff 1.2oz', 'Tobacco', 649, true),
  p('Copenhagen Original Snuff 1.2oz', 'Tobacco', 699, true),
  // VAPING
  p('Vuse Alto Menthol Pod 1pk', 'Vaping', 1299, true),
  p('NJOY Daily Extra Strong Disposable', 'Vaping', 899, true),
  p('Logic Power Menthol Pod 1pk', 'Vaping', 1299, true),
  p('ZYN Nicotine Pouches Cool Mint 6mg 15ct', 'Vaping', 699, true),
  p('On! Nicotine Pouches 4mg 20ct', 'Vaping', 499, true),
  // ELECTRONICS
  p('Duracell AA Batteries 4pk', 'Electronics', 799),
  p('Duracell AAA Batteries 4pk', 'Electronics', 799),
  p('Energizer AA Batteries 4pk', 'Electronics', 799),
  p('Energizer AAA Batteries 4pk', 'Electronics', 799),
  p('USB-A to Lightning Cable 3ft', 'Electronics', 1299),
  p('USB-C Charging Cable 3ft', 'Electronics', 1299),
  p('USB-A to USB-C Adapter', 'Electronics', 999),
  p('Dual USB Car Charger', 'Electronics', 999),
  p('Earbuds Wired 3.5mm', 'Electronics', 999),
  p('Earbuds Bluetooth', 'Electronics', 1999),
  p('Portable Power Bank 2000mAh', 'Electronics', 1999),
  p('USB Wall Charger 5W', 'Electronics', 999),
  p('Screen Cleaning Wipes 10ct', 'Electronics', 299),
  p('Adjustable Phone Stand', 'Electronics', 699),
  // AUTO
  p('Quaker State Synthetic 5W-30 Motor Oil 1qt', 'Auto', 899),
  p('Armor All Interior Wipes 20ct', 'Auto', 599),
  p('Little Trees Black Ice Air Freshener', 'Auto', 249),
  p('Fix-A-Flat Tire Inflator 16oz', 'Auto', 1499),
  p('Rain-X De-Icer Washer Fluid 32oz', 'Auto', 499),
  p('Turtle Wax Spray Car Wax 1oz', 'Auto', 399),
  // HOUSEHOLD
  p('Glad Trash Bags 4-gallon 10ct', 'Household', 499),
  p('Ziploc Sandwich Bags 10ct', 'Household', 399),
  p('Ziploc Gallon Storage Bags 5ct', 'Household', 399),
  p('Reynolds Wrap Aluminum Foil 12in', 'Household', 599),
  p('Bounty Select-A-Size Paper Towels 1 roll', 'Household', 299),
  p('Charmin Ultra Soft Bathroom Tissue 4-pack', 'Household', 599),
  p('Tide Pods Laundry Detergent 3ct', 'Household', 399),
  p('Dawn Original Dish Soap 2oz', 'Household', 249),
  p('Lysol Disinfecting Wipes 15ct', 'Household', 499),
  p('SOLO Cups 18oz 10ct', 'Household', 499),
  p('Paper Plates 9in 10ct', 'Household', 299),
  p('Plastic Utensil Set Fork Knife Spoon', 'Household', 149),
  // BABY
  p('Pampers Swaddlers Diapers Size 1 4ct', 'Baby', 499),
  p('Huggies Snug & Dry Diapers Size 1 4ct', 'Baby', 499),
  p('Enfamil Infant Formula 2oz Nursette', 'Baby', 299),
  p('Pedialyte Electrolyte Solution 11.5oz', 'Baby', 799),
  // MISC
  p('BIC Classic Lighter', 'Misc', 349, true),
  p('BIC Ballpoint Pen', 'Misc', 149),
  p('Playing Cards', 'Misc', 499),
  p('Toothpicks 100ct', 'Misc', 149),
  p('Cotton Swabs 30ct', 'Misc', 299),
  p('Sticky Notes 3x3 20ct', 'Misc', 249),
  p('Scotch Tape 0.75in x 300in', 'Misc', 299),
  p('Safety Pins Assorted 12ct', 'Misc', 149),
]

async function main() {
  const store = await prisma.store.upsert({
    where: { id: 'store_demo' },
    update: {},
    create: {
      id: 'store_demo',
      name: 'Corner Stop 24',
      location: '123 Main St',
      windowModeEnabled: true,
      windowModeStart: '22:00',
      windowModeEnd: '06:00',
      timezone: 'America/Chicago',
    },
  })

  await prisma.product.deleteMany({ where: { storeId: store.id } })

  let count = 0
  for (const prod of catalog) {
    await prisma.product.upsert({
      where: { storeId_name: { storeId: store.id, name: prod.name } },
      update: prod,
      create: { storeId: store.id, active: true, ...prod },
    })
    count++
  }

  console.log(`Seeded store: ${store.id} with ${count} products`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
