ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "onboardingComplete" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "ownerName" TEXT;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "ownerEmail" TEXT;
